
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyNhanSu.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BangChamCong
{

    public int MaChamCong { get; set; }

    public string MaNhanVien { get; set; }

    public Nullable<System.DateTime> NgayChamCong { get; set; }

    public string GhiChu { get; set; }



    public virtual NhanVien NhanVien { get; set; }

}

}
