
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyNhanSu.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Conversation
{

    public Conversation()
    {

        this.Messages = new HashSet<Message>();

    }


    public int Id { get; set; }

    public string Participant1Id { get; set; }

    public string Participant2Id { get; set; }

    public Nullable<System.DateTime> StartedAt { get; set; }

    public Nullable<bool> IsGlobal { get; set; }

    public Nullable<bool> Hidden { get; set; }



    public virtual NhanVien NhanVien { get; set; }

    public virtual NhanVien NhanVien1 { get; set; }

    public virtual ICollection<Message> Messages { get; set; }

}

}
