
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyNhanSu.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Message
{

    public int Id { get; set; }

    public string SenderId { get; set; }

    public string ReceiverId { get; set; }

    public string Content { get; set; }

    public string ImagePath { get; set; }

    public Nullable<System.DateTime> SentAt { get; set; }

    public int ConversationId { get; set; }



    public virtual Conversation Conversation { get; set; }

    public virtual NhanVien NhanVien { get; set; }

    public virtual NhanVien NhanVien1 { get; set; }

}

}
