
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyNhanSu.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Post
{

    public Post()
    {

        this.Comments = new HashSet<Comment>();

        this.Likes = new HashSet<Like>();

    }


    public int PostID { get; set; }

    public string UserID { get; set; }

    public string Content { get; set; }

    public string ImageURL { get; set; }

    public Nullable<System.DateTime> PostDate { get; set; }

    public Nullable<int> LikesCount { get; set; }



    public virtual ICollection<Comment> Comments { get; set; }

    public virtual ICollection<Like> Likes { get; set; }

    public virtual NhanVien NhanVien { get; set; }

}

}
